### PR TITLE
Log with header value if present

### PR DESCRIPTION
**Pull request by talex5**

### CODE REVIEW

**Comment by hannesm** [comment]
this looks fine to me! I'm not sure whether `[source] [header]` would be nicer to read than `[source:header]` -- at least I'm trained now to look for `[]` to find out which log source reported what.. WDYT?

**Comment by talex5** [comment]
I'm using the header to provide more context for the source. e.g. mirage-firewall uses this to report which client ethernet device the message is about:

```
2019-05-01 11:12:37 -00:00: INF [client_eth:10.137.0.12] who-has 10.137.0.19? responding with fe:ff:ff:ff:ff:ff
```

The logs documentation just says that `header` is "an optional printable message", but if you want it at the start of the message then you can just add it to the format string, so I think we should do something different with it.

/cc @dbuenzli

**Comment by talex5** [comment]
Note: I think Travis is confused because I moved this repo to mirage (a long time ago), made this PR, and then forked a copy back to my account. It's trying to pull from https://github.com/mirage/mirage-logs/tree/log-header, which doesn't exist.

**Review by dinosaure — APPROVED** [review]

**Comment by hannesm** [comment]
@talex5 interesting -- why would you not use tags for the ip address (that'd at least be my first approach to that) -- [Lwt.with_value](http://ocsigen.org/lwt/4.1.0/api/Lwt#VALwith_value) (a form of dynamic-bind) is pretty useful in that setting..

**Comment by talex5** [comment]
@hannesm I want the client ID to appear in the log header, whereas tags appear at the end (because I often want to scan for events from a particular client). I don't know why Logs has both a tags mechanism and a header, rather than making header just another tag.

**Comment by dbuenzli** [comment]
> I don't know why Logs has both a tags mechanism and a header, rather than making header just another tag.

@talex5 that's a fair question. Not sure I have a good answer to it. 

But I'd say tags are quite different, in particular they are typed (i.e. you want your tag for the IP address to be typed not be a string). They are rather meant to be used for structured (vs text) log reporting and query. For example AFAIR they are not rendered by the default reporters. 

I'm not sure whether the header was a good idea or not but it allows loggers to do "something special" in a standard way that default reporters will show (and custom reporters can understand).

That being said nothing prevents your custom reporter from rendering the header in a special manner when it finds say an IP address tag in the tag set.

**Comment by talex5** [comment]
@dbuenzli : thanks for the clarifications!

**Pull request merged**
